spring.application.name=project

# DB(MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/mpdb?autoReconnect=true&useSSL=true
spring.datasource.username=root
spring.datasource.password=fmstec

# Mybatis
mybatis.type-aliases-package=movie.project.domain
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.jdbc-type-for-null=null

#API Key
movie.api.key=0ca056c179b9c4a3baec3ea52b4ff815