spring.application.name=project

# Mybatis
mybatis.type-aliases-package=movie.project.domain
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.jdbc-type-for-null=null

#profile ??
spring.profiles.include=db